### 회의실 정보 "전체 확인"
GET http://localhost:3000/rooms

### "특정" 회의실 정보 확인
GET http://localhost:3000/rooms/678e3d5e584bf6e5afd5a9ff

### 예약 정보 "전체 확인"
GET http://localhost:3000/reservation

### "특정" 예약 확인
GET http://localhost:3000/reservation/678e535a0f5bc6159dcea292

### "특정" 회의실에 전체 예약 확인
GET http://localhost:3000/reservation/room/678e3d5e584bf6e5afd5a9ff

### "특정" 회의실에 예약하기
POST http://localhost:3000/reservation/678e3d5e584bf6e5afd5a9ff
Content-Type: application/json

{
    "title": "피드백",
    "description": "회의실에서 피드백하기",
    "startTime": "2025-01-20T13:00:00+09:00",
    "endTime": "2025-01-20T14:00:00+09:00",
    "booker" : "장용한"
}

### '특정' 회의실에 대한 예약 삭제
DELETE http://localhost:3000/reservation/678e5edbd18f035904b70830